%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-python-mrpt
Version:        2.14.9
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS python_mrpt package

License:        BSD
URL:            https://www.mrpt.org/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-mrpt-libapps
Requires:       ros-kilted-mrpt-libgui
Requires:       ros-kilted-mrpt-libnav
Requires:       ros-kilted-mrpt-libslam
Requires:       ros-kilted-ros-workspace
BuildRequires:  assimp-devel
BuildRequires:  cmake3
BuildRequires:  ffmpeg-free-devel
BuildRequires:  freeglut-devel
BuildRequires:  glfw-devel
BuildRequires:  libXrandr-devel
BuildRequires:  libXxf86vm-devel
BuildRequires:  libfreenect-devel
BuildRequires:  libfreenect-openni
BuildRequires:  libjpeg-turbo-devel
BuildRequires:  libpcap-devel
BuildRequires:  libusbx-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  octomap-devel
BuildRequires:  opencv-devel
BuildRequires:  pkgconfig
BuildRequires:  pybind11-devel
BuildRequires:  python3-pip
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-cv-bridge
BuildRequires:  ros-kilted-mrpt-libapps
BuildRequires:  ros-kilted-mrpt-libgui
BuildRequires:  ros-kilted-mrpt-libnav
BuildRequires:  ros-kilted-mrpt-libslam
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-ros-environment
BuildRequires:  ros-kilted-rosbag2-storage
BuildRequires:  systemd-devel
BuildRequires:  tinyxml2-devel
BuildRequires:  wxGTK3-devel
BuildRequires:  zlib-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Python wrapper for Mobile Robot Programming Toolkit (MRPT) libraries

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Sat May 17 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.9-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.7-2
- Autogenerated by Bloom

* Mon Dec 09 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.7-1
- Autogenerated by Bloom

* Tue Dec 03 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.6-1
- Autogenerated by Bloom

* Tue Nov 05 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.5-1
- Autogenerated by Bloom

* Sat Oct 19 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.4-1
- Autogenerated by Bloom

* Sat Oct 12 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.3-1
- Autogenerated by Bloom

* Sat Oct 05 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.2-1
- Autogenerated by Bloom

* Wed Sep 25 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.1-1
- Autogenerated by Bloom

* Sun Sep 15 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.0-1
- Autogenerated by Bloom

* Sat Sep 07 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.13.8-1
- Autogenerated by Bloom

* Sun Sep 01 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.13.7-1
- Autogenerated by Bloom

